apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixyr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mixyr
  template:
    metadata:
      labels:
        app: mixyr
    spec:
      containers:
      - image: okteto.dev/mixyr:latest
        name: mixyr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0847f908-1887-4f9f-9953-9547dbe27ca7"
        - name: Vless_Path
          value: "/0847f908-1887-4f9f-9953-9547dbe27ca7-vless"
        - name: Vmess_UUID
          value: "0847f908-1887-4f9f-9953-9547dbe27ca7"
        - name: Vmess_Path
          value: "/0847f908-1887-4f9f-9953-9547dbe27ca7-vmess"
        - name: Share_Path
          value: "/v2link"
